service: mjml

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 2048
  stage: prod
  region: sa-east-1
  lambdaHashingVersion: 20201221

functions:
  to-html:
    description: 'MJML to HTML'
    handler: handler.convert
